stages:
  - ansiblemaster
  - ansibleslave

#variables:
 # TF_VERSION: "1.0.9"  # Define the Terraform version you want to install

before_script:
  - sudo apt update
  - sudo apt install -y ansible-core
  #- sudo apt update && sudo apt install -y curl unzip  # Install necessary tools (for Alpine-based images)
  #- curl -fsSL "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip" -o terraform.zip
  #- unzip terraform.zip
  #- chmod +x terraform
  #- mv terraform /usr/local/bin/terraform
  #- terraform --version  # Verify Terraform installation

ansiblemaster:
  stage: ansiblemaster
  tags:
    - mtech
  script:
    - ansible-playbook -i inventory ansiblemaster.yml

ansibleslave:
  stage: ansibleslave
  tags:
    - mtech
  script:
    - ansible-playbook -i inventory ansibleslave.yml
